import { beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
const mocks = vi.hoisted(() => ({ auth: { isAuthenticated: false, isSimpleMode: false, user: { id: 1, balance: 0 } }, app: { siteName: 'Example', cachedPublicSettings: { api_base_url: 'https://gateway.example.com', custom_endpoints: [], community_links: [] }, fetchPublicSettings: vi.fn() }, keys: vi.fn(), groups: vi.fn(), subscriptions: vi.fn(), stats: vi.fn(), monitors: vi.fn() }))
vi.mock('vue-i18n', async (importOriginal) => ({ ...await importOriginal<typeof import('vue-i18n')>(), useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/stores/auth', () => ({ useAuthStore: () => mocks.auth }))
vi.mock('@/stores/app', () => ({ useAppStore: () => mocks.app }))
vi.mock('@/api/keys', () => ({ list: mocks.keys }))
vi.mock('@/api/groups', () => ({ getAvailable: mocks.groups }))
vi.mock('@/api/subscriptions', () => ({ getActiveSubscriptions: mocks.subscriptions }))
vi.mock('@/api/usage', () => ({ usageAPI: { getDashboardStats: mocks.stats } }))
vi.mock('@/utils/featureFlags', () => ({ FeatureFlags: { payment: 'payment', modelPlaza: 'model' }, isFeatureFlagEnabled: () => false }))
import ConnectView from '../ConnectView.vue'
import GettingStarted from '@/components/user/dashboard/GettingStarted.vue'
const global = { stubs: { AppLayout: { template: '<main><slot /></main>' }, PlazaNavBar: true, UseKeyContent: { props: ['apiKey', 'platform', 'baseUrl'], template: '<div data-testid="guide">{{ apiKey }}|{{ platform }}|{{ baseUrl }}</div>' }, CommunitySection: true, BillingExplanation: true, RouterLink: { props: ['to'], template: '<a :href="to"><slot /></a>' } } }
beforeEach(() => { vi.clearAllMocks(); mocks.auth.isAuthenticated = false; mocks.keys.mockResolvedValue({ items: [], total: 0 }); mocks.groups.mockResolvedValue([]); mocks.subscriptions.mockResolvedValue([]); mocks.stats.mockResolvedValue({ total_requests: 0 }) })
describe('connection and onboarding behavior', () => {
 it('allows anonymous reading without requesting private keys', async () => { const w = mount(ConnectView, { global }); await flushPromises(); expect(mocks.keys).not.toHaveBeenCalled(); expect(w.get('[data-testid="guide"]').text()).toContain('YOUR_API_KEY'); expect(w.text()).toContain('commercial.connect.preview'); w.unmount() })
 it('shows only usable personal keys and keeps generic mode as the default', async () => { mocks.auth.isAuthenticated = true; mocks.keys.mockResolvedValue({ items: [{ id: 1, name: 'active', key: 'test-only-key', status: 'active', group: { platform: 'openai' } }, { id: 2, name: 'disabled', key: 'disabled-key', status: 'inactive', group: { platform: 'openai' } }, { id: 3, name: 'expired', status: 'active', expires_at: '2020-01-01', group: { platform: 'openai' } }], total: 3 }); const w = mount(ConnectView, { global }); await flushPromises(); const select = w.findAll('select')[0]; expect(select.text()).toContain('active'); expect(select.text()).not.toContain('disabled'); expect(select.text()).not.toContain('expired'); expect(w.get('[data-testid="guide"]').text()).toContain('YOUR_API_KEY'); await select.setValue('1'); expect(w.get('[data-testid="guide"]').text()).toContain('test-only-key|openai|https://gateway.example.com'); w.unmount() })
 it('keeps generic instructions available after a private API failure', async () => { mocks.auth.isAuthenticated = true; mocks.keys.mockRejectedValue(new Error('offline')); const w = mount(ConnectView, { global }); await flushPromises(); expect(w.get('[role="alert"]').text()).toContain('commercial.connect.failed'); expect(w.get('[data-testid="guide"]').text()).toContain('YOUR_API_KEY'); w.unmount() })
 it('explains missing access without inventing completion or exposing a disabled purchase entry', async () => { const w = mount(GettingStarted, { global }); await flushPromises(); expect(w.text()).toContain('commercial.onboarding.noGroups'); expect(w.text()).toContain('commercial.onboarding.noFunding'); expect(w.find('a[href="/purchase"]').exists()).toBe(false); expect(w.findAll('li').every(li => li.text().includes('commercial.onboarding.next'))).toBe(true); await w.get('input[type="checkbox"]').setValue(true); expect(w.findAll('li')[2].text()).toContain('commercial.onboarding.done'); w.unmount() })
 it('does not interpret a failed account lookup as no access', async () => { mocks.groups.mockRejectedValue(new Error('offline')); const w = mount(GettingStarted, { global }); await flushPromises(); expect(w.get('[role="alert"]').text()).toContain('commercial.onboarding.failed'); expect(w.text()).not.toContain('commercial.onboarding.noGroups'); w.unmount() })
})
